/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author chanu
 */
public class Simple_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Simple_Calculator
     */
    double numb,ans;
    int calculation;
    public Simple_Calculator() {
        initComponents();
    }
    public void arithmatic_operation(){
        switch (calculation){
            case 1://Addition
                ans=numb+Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
            case 2://Subtracition
                ans=numb-Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
            case 3://Multiplication
                ans=numb*Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break; 
            case 4://Divition
                ans=numb/Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
                 }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton_answer = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setPreferredSize(new java.awt.Dimension(50, 40));

        jButton27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton27.setText("jButton1");
        jButton27.setPreferredSize(new java.awt.Dimension(50, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMPLE CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 290, 70));

        jButton61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton61.setText("±");
        jButton61.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jButton62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton62.setText("<-");
        jButton62.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jButton63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton63.setText("CE");
        jButton63.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jButton64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton64.setText("√");
        jButton64.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jButton65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton65.setText("C");
        jButton65.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jButton80.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton80.setText("9");
        jButton80.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButton81.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton81.setText("/");
        jButton81.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jButton82.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton82.setText("7");
        jButton82.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButton83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton83.setText("8");
        jButton83.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jButton85.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton85.setText("jButton1");
        jButton85.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButton90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton90.setText("%");
        jButton90.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton90ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jButton101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton101.setText("*");
        jButton101.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton101ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jButton102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton102.setText("4");
        jButton102.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton102ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jButton103.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton103.setText("5");
        jButton103.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton103ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jButton104.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton104.setText("X²");
        jButton104.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton104ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jButton105.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton105.setText("6");
        jButton105.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton105ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jButton107.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton107.setText("0");
        jButton107.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton107ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        jButton110.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton110.setText("+");
        jButton110.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton110ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jButton121.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton121.setText("-");
        jButton121.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton121ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton121, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jButton123.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton123.setText("2");
        jButton123.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton123ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton123, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jButton_answer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_answer.setText("=");
        jButton_answer.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 90));

        jButton146.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton146.setText("1");
        jButton146.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton146ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton146, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton147.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton147.setText("3");
        jButton147.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton147.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton147ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton147, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jButton148.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton148.setText(",");
        jButton148.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton148.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton148ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton148, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 290, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 370, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        // TODO add your handling code here:
                numb = Double.parseDouble(jTextField1.getText());
                double numb2=Math.sqrt( numb);
                jTextField1.setText(numb2+"");
         
        
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_jButton82ActionPerformed

    private void jButton102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton102ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_jButton102ActionPerformed

    private void jButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton103ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_jButton103ActionPerformed

    private void jButton105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton105ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_jButton105ActionPerformed

    private void jButton146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton146ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_jButton146ActionPerformed

    private void jButton123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton123ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_jButton123ActionPerformed

    private void jButton147ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton147ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_jButton147ActionPerformed

    private void jButton107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton107ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_jButton107ActionPerformed

    private void jButton148ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton148ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+",");
    }//GEN-LAST:event_jButton148ActionPerformed

    private void jButton110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton110ActionPerformed
        // TODO add your handling code here:
        numb = Double.parseDouble(jTextField1.getText());
        calculation = 1;
        jTextField1.setText("");
        jLabel2.setText(numb +"+");
    }//GEN-LAST:event_jButton110ActionPerformed

    private void jButton121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton121ActionPerformed
        // TODO add your handling code here:
          numb = Double.parseDouble(jTextField1.getText());
        calculation = 2;
        jTextField1.setText("");
        jLabel2.setText(numb +"-");
    }//GEN-LAST:event_jButton121ActionPerformed

    private void jButton101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton101ActionPerformed
        // TODO add your handling code here:
          numb = Double.parseDouble(jTextField1.getText());
        calculation = 3;
        jTextField1.setText("");
        jLabel2.setText(numb +"*");
    }//GEN-LAST:event_jButton101ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
          numb = Double.parseDouble(jTextField1.getText());
        calculation = 4;
        jTextField1.setText("");
        jLabel2.setText(numb +"/");
    }//GEN-LAST:event_jButton81ActionPerformed

    private void jButton_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answerActionPerformed
        // TODO add your handling code here:
        arithmatic_operation();
        jLabel2.setText("");
    }//GEN-LAST:event_jButton_answerActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
        int length = jTextField1.getText().length();
        int number = jTextField1.getText().length() -1;
        String backspace;
        if(length > 0)
        {
            StringBuilder back = new StringBuilder(jTextField1.getText());
            back.deleteCharAt(number);
            backspace = back.toString();
            jTextField1.setText(backspace);
            
        }
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jLabel2.setText("");
        
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
        // TODO add your handling code here:
        numb = Double.parseDouble(jTextField1.getText())/100;
        jTextField1.setText(numb+"");
    }//GEN-LAST:event_jButton90ActionPerformed

    private void jButton104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton104ActionPerformed
        // TODO add your handling code here:
         numb = Double.parseDouble(jTextField1.getText());
         double numb1=Math.pow( numb,2);
         jTextField1.setText(numb1+"");
         
        
    }//GEN-LAST:event_jButton104ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        String value = jTextField1.getText();
        if(!value.contains("-"))
        {
            jTextField1.setText("-"+value);
        }
        else
        {
         try{
               jTextField1.setText(value.split("-")[1]);
         } 
         catch(IndexOutOfBoundsException e){
               jTextField1.setText("");
         }
        }
        
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simple_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simple_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simple_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simple_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simple_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton_answer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
